version: '3'
services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_NAME=${NEXT_PUBLIC_NAME}
      - NEXT_PUBLIC_MEDIA_HOSTNAME=${NEXT_PUBLIC_MEDIA_HOSTNAME}
      - NEXT_PUBLIC_MEDIA_PORT=${NEXT_PUBLIC_MEDIA_PORT}
      - NEXT_PUBLIC_MEDIA_PROTOCOL=${NEXT_PUBLIC_MEDIA_PROTOCOL}
      - NEXT_PUBLIC_MEDIA="${NEXT_PUBLIC_MEDIA_PROTOCOL}://${NEXT_PUBLIC_MEDIA_HOSTNAME}:${NEXT_PUBLIC_MEDIA_PORT}"
      - NEXT_PUBLIC_MAIL_RU_CLIENT_ID=${NEXT_PUBLIC_MAIL_RU_CLIENT_ID}
      - NEXT_PUBLIC_MAIL_RU_SECRET=${NEXT_PUBLIC_MAIL_RU_SECRET}
      - NEXT_PUBLIC_YANDEX_CLIENT_ID=${NEXT_PUBLIC_YANDEX_CLIENT_ID}
      - NEXT_PUBLIC_YANDEX_CLIENT_SECRET=${NEXT_PUBLIC_YANDEX_CLIENT_SECRET}
      - NEXT_PUBLIC_VK_CLIENT_ID=${NEXT_PUBLIC_VK_CLIENT_ID}
      - NEXT_PUBLIC_VK_CLIENT_SECRET=${NEXT_PUBLIC_VK_CLIENT_SECRET}
