name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          set -x
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@94.241.171.106 'cd /home/ubuntu/client/; docker-compose down ; git config pull.rebase false ; git reset --hard HEAD ; git clean -fd ; git pull origin main; docker-compose up -d --build ; docker image prune -a'
